POST http://localhost:8788/users
Content-Type: application/json

{
  "user": {
    "username": "test",
    "email": "test@example.com",
    "password": "password"
  }
}

###

POST http://localhost:8788/users/login
Content-Type: application/json

{
  "user": {
    "email": "bob@example.com",
    "password": "password"
  }
}

###

GET http://localhost:8788/user
Authorization: Token eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2dpdGh1Yi5jb20vaGd3b29kL3JlYWx3b3JsZC1jb25kdWl0LXNxbGZlIiwic3ViIjoiMiIsImlhdCI6MTY0ODA0NDcyOSwiZXhwIjoxNjQ4MTMxMTI5LCJqdGkiOiI4YTAxMjc4OC1kZTE5LTQ1NzEtYTU3Zi05ZjUyOTJlZWQzODcifQ.hALvhzNUwgHM1rk-dibE3cimmvcy8q7z43g_5C4XCMzBmVW31Wayp4kGtYS_CwUqjgnSzcNmQab_kdew2Jd8yQ

###

GET http://localhost:8788/articles

###

GET http://localhost:8788/articles
Authorization: Token alice@example.com

###

GET http://localhost:8788/articles
Authorization: Token bob@example.com

###

GET http://localhost:8788/articles?author=Alice
Authorization: Token alice@example.com

###

GET http://localhost:8788/articles?author=Bob
Authorization: Token alice@example.com

###

GET http://localhost:8788/articles?favorited=Bob
Authorization: Token alice@example.com

###

GET http://localhost:8788/articles?favorited=Claire
Authorization: Token alice@example.com

###

GET http://localhost:8788/articles?limit=1
Authorization: Token alice@example.com

###

GET http://localhost:8788/articles?offset=1&limit=1
Authorization: Token alice@example.com

###

GET http://localhost:8788/articles/feed
Authorization: Token bob@example.com

###

GET http://localhost:8788/articles/feed
