POST http://localhost:8788/users
Content-Type: application/json

{
  "user": {
    "username": "test",
    "email": "test@example.com",
    "password": "password"
  }
}

###

GET http://localhost:8788/articles
Authorization: Token alice@example.com

###

GET http://localhost:8788/articles
Authorization: Token bob@example.com

###

GET http://localhost:8788/articles?author=Alice
Authorization: Token alice@example.com

###

GET http://localhost:8788/articles?author=Bob
Authorization: Token alice@example.com

###

GET http://localhost:8788/articles?favorited=Bob
Authorization: Token alice@example.com

###

GET http://localhost:8788/articles?favorited=Claire
Authorization: Token alice@example.com
